// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StavHelloWorld) DeepCopyInto(out *StavHelloWorld) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StavHelloWorld.
func (in *StavHelloWorld) DeepCopy() *StavHelloWorld {
	if in == nil {
		return nil
	}
	out := new(StavHelloWorld)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StavHelloWorld) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StavHelloWorldList) DeepCopyInto(out *StavHelloWorldList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StavHelloWorld, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StavHelloWorldList.
func (in *StavHelloWorldList) DeepCopy() *StavHelloWorldList {
	if in == nil {
		return nil
	}
	out := new(StavHelloWorldList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StavHelloWorldList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StavHelloWorldSpec) DeepCopyInto(out *StavHelloWorldSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StavHelloWorldSpec.
func (in *StavHelloWorldSpec) DeepCopy() *StavHelloWorldSpec {
	if in == nil {
		return nil
	}
	out := new(StavHelloWorldSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StavHelloWorldStatus) DeepCopyInto(out *StavHelloWorldStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StavHelloWorldStatus.
func (in *StavHelloWorldStatus) DeepCopy() *StavHelloWorldStatus {
	if in == nil {
		return nil
	}
	out := new(StavHelloWorldStatus)
	in.DeepCopyInto(out)
	return out
}
